### ISSUE TITLE
Iterating over all() WebProfiles when there are none raises KeyError

### ISSUE THREAD

**Issue by HenrikOssipoff** [paypal/PayPal-Python-SDK#102]
Not sure if this applies to all List operations, or it is limited to WebProfiles -- or if it's limited to using local API objects.

```python
for web_profile in paypalrestsdk.WebProfile.all(api=self.api):
    pass
```
This will raise a KeyError with the following stack trace:

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/henrik/Development/pgw/pgw/provider/modules/paypalrest/models.py", line 93, in _experience_profile_id
    for web_profile in paypalrestsdk.WebProfile.all(api=self.api):
  File "/Users/henrik/Development/pgw/env/lib/python3.4/site-packages/paypalrestsdk/resource.py", line 80, in __getitem__
    return self.__data__[key]
KeyError: 0
```

I'm not sure if this is your intended behaviour, but as a user, I would expect this to just not yield any results, instead of throwing a KeyError.

**Comment by avidas** [comment]
@HenrikOssipoff does this happen all the time with iterating over WebProfiles?

**Comment by HenrikOssipoff** [comment]
It happens on all occasions where there is none on the account (sorry if this wasn't clear enough).

This could of course be a design choice, but it seems more natural that "no available web profiles" would return an empty list rather than raising an exception. Something that returns a list on success should never return anything else, in my humble opinion :)

Changing this could potentially prove backwards incompatible if people rely on the exception to know if an account has any web profiles, though.

**Comment by avidas** [comment]
None on the account for web profiles or for any resource? Good point on backwards compatibility!

**Comment by avidas** [comment]
Doing some debugging, does seem to happen across all resources while doing List operations, and is independent of local API objects being passed.

**Comment by HenrikOssipoff** [comment]
Sorry haven't been at a computer lately due to vacation from work.




I was expecting as much. Not sure if it would be nettet to leave alone due to backwards compatability. Luckikly not up to me :) it does however seem like a weird design choice.



–
Sendt fra Mailbox

**Comment by avidas** [comment]
I looked into this some more and I think one of the issues here is way that Resource is currently set up so that it can both refer to an individual paypal api object, or a list of paypal api objects. The design decision predates me, so I am not sure what the original motivations were, but the problem with iteration stems from that. Right now, workarounds could be to either handle for KeyError or check the result after calling all() on a resource. But we could probably split Resource and possibly a ResourceList class for a major release so that we can address the issue with iteration without a breaking change.
