### ISSUE TITLE
PayPal return nothing.

### ISSUE THREAD

**Issue by test101test101** [paypal/PayPal-Python-SDK#129]
I have this script:

```
import paypalrestsdk
paypalrestsdk.configure({
  "mode": "live", # sandbox or live
  "client_id": "MY KEY",
  "client_secret": "MY SECRET" })

payment_history = paypalrestsdk.Payment.all({"count": 10})
payment_history.payments
for payment in payment_history.payments:
    print("  -> Payment[%s]" % (payment.create_time))
```

But I get this error:
```
No handlers could be found for logger "paypalrestsdk.api"

    for payment in payment_history.payments:
TypeError: 'NoneType' object is not iterable
```

If I run the script in `sandbox `I get diffrent error:
```
raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

```

**Comment by bluk** [comment]
For the first error `TypeError: 'NoneType' object is not iterable`, it is because you do not have any payments created by your app yet. Once you have at least one payment, the `payment_history.payments` will not be `None`, and you can iterate through the list. I suggest trying to create some in sandbox (as you tried).

For the `sandbox` error with the TLS, please make sure that your environment can support TLS v1.2. You can find out more at the [PayPal TLS Update repository](https://github.com/paypal/TLS-update) with additional support links. Specifically, the [Python section](https://github.com/paypal/TLS-update#python) has some code snippets which can help ensure that you've met the requirements. In general, this means you must have OpenSSL 1.01c or higher and Python 2.7 or higher.

Please leave a comment if you have any additional questions.

**Comment by test101test101** [comment]
@bluk I have several stores which all payments received through PayPal.  I see the transactions in my PayPal account, I just want to get these transactions with the script.

**Comment by bluk** [comment]
@test101test101 If you're sure that you're using the client ID/secret associated with the store, then I would open a ticket with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) who can assist with your account specific problem. Any payments created via the REST API should be returned (as long as they were created with the same client ID and client secret app credentials).

**Comment by test101test101** [comment]
@bluk I didn't have client ID/secret until now. I created them to use this SDK.

**Comment by test101test101** [comment]
@bluk My system is using WC https://docs.woothemes.com/document/paypal-standard/   this uses IPN to verify data. There is no where to put client ID and client secret. This is how transactions are made.

I simply want to write a script which get history of payments. Payments were made with the system in the link.

**Comment by juwlee** [comment]
@test101test101 the doc that you posted seems to have been written for classic APIs. This SDK works with newer REST APIs. You need a different set of credentials. To get your own, please refer to [PayPal docs](https://developer.paypal.com/docs/integration/direct/make-your-first-call/).

Also, please see [here](https://github.com/paypal/PayPal-Python-SDK/tree/master/samples) for sample code that includes payments and webhooks. Webhooks in REST is a counterpart of IPN in classic APIs.

**Comment by test101test101** [comment]
@juwlee  Where do I get these credentials? From PayPal developer dashboard I can create only for REST or SOAP APIs. 
I'm not sure I understand how to use this Webhooks.

Currently my code is as I posted. I use the `all `function in the SDK.

**Comment by juwlee** [comment]
This is a REST SDK, so you need REST credentials (`client_id` and `client_secret` pair). [The aforementioned doc](https://developer.paypal.com/docs/integration/direct/make-your-first-call/#get-an-access-token) should give an idea how to get them.

**Comment by test101test101** [comment]
@juwlee  I know how to get the client_id and client_secret. I used them already and it gave me nothing in the results. As we already figured out my other payments were made with classic APIs. So my question is will this SDK can help me get the history of this transactions if not what can I do?

**Comment by bluk** [comment]
@test101test101 From the link you gave, the WooCommerce plugin uses the [SOAP/NVP](https://developer.paypal.com/docs/classic/lifecycle/apps101/) credentials, so you should use the SOAP/NVP API and perform operations like [TransactionSearch](https://developer.paypal.com/docs/classic/api/merchant/TransactionSearch_API_Operation_SOAP/). Unfortunately, there isn't a Python SOAP/NVP SDK, but there are [other languages available](https://developer.paypal.com/docs/classic/lifecycle/sdks/).

**Comment by test101test101** [comment]
@bluk Thank you. I don't mind using other languages. Do you mean the "Invoicing" SDK?

**Comment by bluk** [comment]
One of the [Merchant SDKs](https://github.com/paypal?utf8=✓&query=merchant-sdk) should be able to help. The [SOAP/NVP SDK reference](https://developer.paypal.com/docs/classic/api/) is what I used to find out what products the query is available in.

Since the Python REST SDK seems to not have any relevance to your issue now, I'm going to close this issue. If you have a specific issue with one of the merchant SDKs, please open an issue in their respective repositories. Thanks!

**Comment by khieu** [comment]
@bluk  I have the `alert handshake failure` for sandbox as well, I have tried to update my OpenSSL to 1.0.2, however I still get the same error. I'm currently running python 2.6. I want to ask if it's possible to make this work for python 2.6 ? 

Thanks much for your help !

**Comment by bluk** [comment]
@khieu Please try the test commands listed [here](https://github.com/paypal/tls-update#python) for Python on the PayPal TLS update site. I tried on a Python 2.7 environment, and it worked for me. It could be that you need to update your Python installation itself depending on how it was built with OpenSSL support. If you're still encountering an issue, I would suggest opening a new issue since this one has many different issues at this point.

**Comment by khieu** [comment]
@bluk thanks 👍 ,  I have tried those commands on python 2.6 and get Paypal connection OK. However I still get the same error. I have created a new issue for that. 
Thanks.
