### ISSUE TITLE
Agreements will not receive payment.sale.completed webhook if created before 8/23/16

### ISSUE THREAD

**Issue by mattLummus** [paypal/PayPal-Python-SDK#163]
## Issue Description
Via #132 [(Specific comment here...)](https://github.com/paypal/PayPal-Python-SDK/issues/132#issuecomment-251130368)
> @ppmtscory  ...the billing agreement ID would be included in the PAYMENT.SALE.COMPLETED webhook. These events will only be sent for subscriptions that were set up after this went live which was towards the end of Aug...

What this means is that currently in order for an existing application to use this webhook:

1) The application will need to cancel their previous subscriptions
2) Notify their customers that their subscriptions have been canceled and that they will need to re-execute a new one
3) Their customers have to actually take the effort to go re-execute before the next payment cycle

If the customer doesn't follow through, the application will lose revenue.

I have not seen this documented anywhere previously and this webhook has been live for 6 weeks at this point. 

This issue may also result in a false positive because setting up new agreements during testing can result in expected behavior but previous agreements in production environments will be affected.

**Comment by ppmtscory** [comment]
Unfortunately, due to the data that was needed to be used to make this happen, this feature was added as part of a new service.  The data needed is not available on the older service, and thus, the reason for not getting these for Subscriptions created prior to the feature being released.  While I can agree with you that this isn't exactly ideal, there's currently no way around it due to the way that it has to work.  You can continue to use the process that you had in place for those subscriptions, prior to this feature being released, and anything new will receive the `PAYMENT.SALE.COMPLETED` webhook.

**Comment by pianostringquartet** [comment]
Hi, just wanted to get clarification: does this limitation pertain to only `PAYMENT.SALE.COMPLETED` events, or _all_ events (including e.g. `BILLING.SUBSCRIPTION.UPDATED`)?
