### ISSUE TITLE
Paypal returns 500 when creating a payment

### ISSUE THREAD

**Issue by blurrcat** [paypal/PayPal-Python-SDK#164]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 4ae18f0ad812e
- Version of Python used: 3.5
- SDK Version: 1.11.7

### Issue Description

Paypal returns 500 when I try to create a payment. The same code was working about 10 hours ago. This may be related to https://github.com/paypal/PayPal-PHP-SDK/issues/676. Though that issue is closed we're still experiencing this. Relevant traceback:
```
File "/usr/src/app/lucky/payment/paypal/api.py", line 119, in post
    if payment.create():
  File "/usr/local/lib/python3.5/site-packages/paypalrestsdk/resource.py", line 163, in create
    new_attributes = self.api.post(self.path, self.to_dict(), headers, refresh_token)
  File "/usr/local/lib/python3.5/site-packages/paypalrestsdk/api.py", line 272, in post
    return self.request(util.join_url(self.endpoint, action), 'POST', body=params or {}, headers=headers or {}, refresh_token=refresh_token)
  File "/usr/local/lib/python3.5/site-packages/paypalrestsdk/api.py", line 164, in request
    return self.http_call(url, method, data=json.dumps(body), headers=http_headers)
  File "/usr/local/lib/python3.5/site-packages/paypalrestsdk/api.py", line 207, in http_call
    return self.handle_response(response, response.content.decode('utf-8'))
  File "/usr/local/lib/python3.5/site-packages/paypalrestsdk/api.py", line 236, in handle_response
    raise exceptions.ServerError(response, content)
paypalrestsdk.exceptions.ServerError: Failed. Response status: 500. Response message: Internal Server Error. Error message: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"4ae18f0ad812e"}
```

**Comment by bluk** [comment]
@blurrcat This is a different issue. It is due to the use of a web profile experience. You can try creating a payment without a experience profile id. I've opened PPPLPAYPT-13546 to track this. Thanks for reporting this with details.

**Comment by blurrcat** [comment]
@bluk does this affect live mode or this is just happening in the sandbox?

**Comment by bluk** [comment]
@blurrcat This should only affect sandbox.

BTW, if you (or anyone else) encounter immediate or live issues, please use https://www.paypal-techsupport.com and report the issue via the `Contact Support` link at the bottom.

**Comment by bluk** [comment]
This issue should have been resolved. Thanks for your patience.

**Comment by davePlug** [comment]
@bluk I know this issue is closed but i have exactly same python version, same SDK version and i'm getting **apparently** the same error:
`paypalrestsdk.exceptions.ServerError: Failed. Response status: 500. Response message: Internal Server Error. Error message: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"5d77e150d7ceb"}`

Is there a way for me to get more information about the error?

**Comment by bluk** [comment]
@davePlug There is an effort to provide better information in the error messages instead of the generic 500 that is returned from the servers. I don't have a timeline though. Your error is specific to your request.

I would check that the credit card used is a test credit card generated via the developer portal. You can [create a new sandbox personal buyer test account](https://developer.paypal.com/docs/classic/lifecycle/sb_create-accounts/) and vault the credit card associated with that account.

If that doesn't solve your issue, please open a new one with an example of your vault request and payment request. Thanks.
