### ISSUE TITLE
Critical problem with token_hash in Api

### ISSUE THREAD

**Issue by amir-hadi** [paypal/PayPal-Python-SDK#171]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): Many
- Version of Python used: 3.4
- SDK Version: 1.9.0

### Issue Description

We are using PayPal for 'classic' payments using the redirect method and now in a new app using future payments. This mixture of services used is dangerous, since the API object is global and caches a value, that maybe shouldn't be cached.

This is the steps to reproduce:
1. Add a PayPal future payment method using the authorization code from the mobile device in `api.get_refresh_token(auth_code)`
1.1. This will call the `get_token_hash` method and pass on the `authorization_code`.
2. Create a Authorization/Payment (in the name of User A) using that `refresh_token` and a valid `correlation_id`.
2.2. This will call `get_token_hash` with the `refresh_token` of a user, and the Authorization/Payment will be done in his name
3. Create another Payment in the name of User B, without a `refresh_token`. This should create a 'classic' payment using a rediect to PayPal.
3.1. But the token_hash of the user before is still cached in the global api object. Through this caching the token_hash of the user A will be sent for the Payment of user B.
3.2. Somehow this leads to that the Payment of user B is instantly payed using the details of user A.

The only workaround of this is creating a new API object per Payment and passing the new API object into the `Payment.create` method, so no caching occurs.

**Comment by jaypatel512** [comment]
Thanks @Muty for pointing this out. 

It is happening because every time we make a call to get access token, we cache the returned value in `self.token_hash`. The same applied for refresh token case, and so, it fails. 

I think the best course of action here should be to not cache the access token in case of refresh token. This should allow you to still used cached token for all other `classic` payment cases, and not get this result in case of `refresh_token`. 

I will go ahead and reproduce this issue, and work on the fix soon. If you are excited to help us out here, we would really love a PR with the fix. 👍

**Comment by Muty** [comment]
I could try to work on this next week and create a PR. My suggested fix would be also to not cache if it is a `refresh_token`.
