### ISSUE TITLE
Payment MALFORMED_REQUEST errror, Incoming JSON request does not map to API request

### ISSUE THREAD

**Issue by gonguinguen** [paypal/PayPal-Python-SDK#190]
Hi there! 
I'm using version 1.12.0, installed from pip.
Everything works ok, but I can't execute the Payment.replace() method in order to update the amount of a payment. This is the error I receive:

debug_id=6d630d1ca64bc
information_link=https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST
message=Incoming JSON request does not map to API request
name=MALFORMED_REQUEST

The code portion where I do the update is this:

`payment = pp.Payment.find(request.args(0))`
`payment.replace({
        "transactions": [{
            "amount": {
                "total": "1.11",
                "currency": "USD",
            },
            "item_list": {
                "items": [
                    {
                        "name": "test",
                        "description": "test",
                        "quantity": "1",
                        "price": "1.11",
                        "currency": "USD"
                    },
                ]
            }
        }]
    })`

Is this a bug in the SDK or am I missing something?

**Comment by pp-randy** [comment]
Try using an array with patch objects shown in the usage note here https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/resource.py#L191

https://developer.paypal.com/docs/api/payments/#definition-json_patch

You can see a patch example in curl here with the JSON needed for the payment update: https://developer.paypal.com/docs/api/payments/#payment_update

Also a note on patching a payment to be aware of:
> Partially updates a payment, by ID. You can update the amount, shipping address, invoice ID, and custom data. You cannot update a payment after the payment executes.

I will do some testing to confirm since I don't see a sample for patching the payment.

**Comment by pp-randy** [comment]
Here would be an example for a payment replace. 
`payment.replace([{'op': 'replace', 'path': '/transactions/0/amount', 'value': {'total': '0.99', 'currency': 'USD'}}]):`


I apologize for the delay in following up with you.
