### ISSUE TITLE
use Balance Accounts API with paypalrestsdk

### ISSUE THREAD

**Issue by chapkovski** [paypal/PayPal-Python-SDK#244]
Sorry for a total newbie question but my attempts to get the balance using PayPal Python SDK fails.
Here is the code:

```
import paypalrestsdk
CLIENT_ID = 'XXX'
CLIENT_SECRET = 'YYY'
a = paypalrestsdk.Api(client_id=CLIENT_ID, client_secret=CLIENT_SECRET)
a.get('https://api.sandbox.paypal.com/v2/wallet/balance-accounts')
```

I use paypalrestsdk version 1.13.1
Thank you!

**Comment by bluk** [comment]
We don't support the [Balance Accounts](https://developer.paypal.com/docs/api/balance-accounts/) API at this time due to it being a partner only API. New APIs will also be added to the [v2 version](https://github.com/paypal/PayPal-Python-SDK/tree/2.0-beta) of the SDK going forward. I've added your request to the backlog.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given
