### ISSUE TITLE
Efficient way of checking for payment has been completed

### ISSUE THREAD

**Issue by memolipd** [paypal/PayPal-Python-SDK#77]
using

payment.transactions[0].related_resources[0].sale.state

is not ideal the other alternatives are to loop over all transactions/related_resources and make sure they are all complete.

Any easier ways?

**Comment by avidas** [comment]
Hey @memolipd once you do an execute on a payment, you can [look up the payment](https://developer.paypal.com/docs/api/#look-up-a-payment-resource). The related_resources section has the sale item which has an id, payment.transactions[0].related_resources[0].sale.id. You can use that id to fetch the status of that sale ([sample](https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/sale/find.py)) instead of having to look up the payment resource.

**Comment by memolipd** [comment]
Thanks Avidas this is what we're currently doing, it gets a bit more completed when we need to check more than one items, it makes some heavy assumptions about where the informations is, which when it comes to money being passed around - thats not cool.

when I get some time I'll rewrite the code to dynamically find all transactions and make sure they are all completed. I'll post up when its done.

Would be nice if the SDK could implement this is as it would be pretty commonly used.

**Comment by avidas** [comment]
Hey @memolipd feel free to send in a pull request once you are done and we will definitely take a look at it. I agree that the sdk should make common use cases as easy to handle as possible.

**Comment by jaypatel512** [comment]
Hey @memolipd ! This seems to be a very good idea. I would also love to have something similar to other SDK languages, and this could benefit everyone out here. Waiting for your Pull Request. Thanks for your contribution.

**Comment by avidas** [comment]
@memolipd any updates on this?

**Comment by memolipd** [comment]
Not had time to work on this, maybe over Easter!

**Comment by avidas** [comment]
@memolipd closing this for now, reopen when necessary or start the PR thread
